---
name: ReScript CI

on: [push, pull_request, workflow_dispatch]

jobs:
  ci:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [21.x, 20.x]

    steps:
      - name: Checkout PR
        uses: actions/checkout@v4

      - name: Use Node.js LTS ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install project dependencies
        run: npm install

      - name: Copy files
        run: make copy-exercises

      - name: Run tests for all exercises
        run: npm run ci
